config/routes.rb
Rails.application.routes.draw do
  root to: "cocktails#index"
  resources :ingredients
  resources :cocktails do
      resources :doses, only: [:new, :create]
  end
  resources :doses, only: [:destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  before_save :default_values
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, presence: true, uniqueness: true
  mount_uploader :photo, PhotoUploader


  def nbr_ingredient
    id = self.id
    @doses = Dose.where(cocktail_id: id)
    sum = 0
    @doses.each { |_dose| sum += 1 }
    sum
  end

  def add_vote
    self.vote += 1
    self.save
  end

  private

  def default_values
    self.vote = 0 if self.vote.nil?
  end
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates_uniqueness_of :cocktail, :ingredient, scope: [:cocktail_id, :ingredient_id]
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [:show, :edit, :update, :destroy]

  # GET /cocktails
  # GET /cocktails.json
  def index
    @cocktails = Cocktail.all
  end

  # GET /cocktails/1
  # GET /cocktails/1.json
  def show
    @doses = Dose.where(cocktail_id: @cocktail.id)
  end

  # GET /cocktails/new
  def new
    @cocktail = Cocktail.new
    @ingredients = Ingredient.all
  end

  # GET /cocktails/1/edit
  def edit
  end

  # POST /cocktails
  # POST /cocktails.json
  def create
    @cocktail = Cocktail.new(cocktail_params)

    respond_to do |format|
      if @cocktail.save
        format.html { redirect_to @cocktail, notice: 'Cocktail was successfully created.' }
        format.json { render :show, status: :created, location: @cocktail }
      else
        format.html { render :new }
        format.json { render json: @cocktail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cocktails/1
  # PATCH/PUT /cocktails/1.json
  def update
    respond_to do |format|
      if @cocktail.update(cocktail_params)
        format.html { redirect_to @cocktail, notice: 'Cocktail was successfully updated.' }
        format.json { render :show, status: :ok, location: @cocktail }
      else
        format.html { render :edit }
        format.json { render json: @cocktail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cocktails/1
  # DELETE /cocktails/1.json
  def destroy
    @cocktail.destroy
    respond_to do |format|
      format.html { redirect_to cocktails_url, notice: 'Cocktail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cocktail
      @cocktail = Cocktail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cocktail_params
      params.require(:cocktail).permit(:name, :photo, :photo_cache)
    end
  end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :set_dose, only: [:show, :edit, :update, :destroy]

  # GET /doses
  # GET /doses.json
  def index
    @doses = Dose.all
  end

  # GET /doses/1
  # GET /doses/1.json
  def show
  end

  # GET /doses/new
  def new
    @dose = Dose.new
    @ingredients = Ingredient.all
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  # GET /doses/1/edit
  def edit
  end

  # POST /doses
  # POST /doses.json
  def create
    @dose = Dose.new(dose_params)
    @dose.cocktail = Cocktail.find(params[:cocktail_id])
    respond_to do |format|
      if @dose.save
        format.html { redirect_to @dose.cocktail, notice: 'Dose was successfully created.' }
        format.json { render :show, status: :created, location: @dose }
      else
        format.html { render :new }
        format.json { render json: @dose.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /doses/1
  # PATCH/PUT /doses/1.json
  def update
    respond_to do |format|
      if @dose.update(dose_params)
        format.html { redirect_to @dose, notice: 'Dose was successfully updated.' }
        format.json { render :show, status: :ok, location: @dose }
      else
        format.html { render :edit }
        format.json { render json: @dose.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /doses/1
  # DELETE /doses/1.json
  def destroy
    @dose.destroy
    respond_to do |format|
      format.html { redirect_to cocktail_path(@dose[:cocktail_id]), notice: 'Dose was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dose
      @dose = Dose.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dose_params
      params.require(:dose).permit(:description, :cocktail_id, :ingredient_id)
    end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_ingredient, only: [:show, :edit, :update, :destroy]

  # GET /ingredients
  # GET /ingredients.json
  def index
    @ingredients = Ingredient.all
  end

  # GET /ingredients/1
  # GET /ingredients/1.json
  def show
  end

  # GET /ingredients/new
  def new
    @ingredient = Ingredient.new
  end

  # GET /ingredients/1/edit
  def edit
  end

  # POST /ingredients
  # POST /ingredients.json
  def create
    @ingredient = Ingredient.new(ingredient_params)

    respond_to do |format|
      if @ingredient.save
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully created.' }
        format.json { render :show, status: :created, location: @ingredient }
      else
        format.html { render :new }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ingredients/1
  # PATCH/PUT /ingredients/1.json
  def update
    respond_to do |format|
      if @ingredient.update(ingredient_params)
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully updated.' }
        format.json { render :show, status: :ok, location: @ingredient }
      else
        format.html { render :edit }
        format.json { render json: @ingredient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ingredients/1
  # DELETE /ingredients/1.json
  def destroy
    @ingredient.destroy
    respond_to do |format|
      format.html { redirect_to ingredients_url, notice: 'Ingredient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ingredient
      @ingredient = Ingredient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ingredient_params
      params.require(:ingredient).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/cocktails/_form.html.erb
<%= simple_form_for (@cocktail) do |f| %>
<%= f.error_notification %>
<div class="form-inputs">
  <%= f.input :name %>
  <%= f.input :photo, class: "arby" %>
  <%= f.input :photo_cache, as: :hidden, class: "arby" %>
</div>

<div class="form-actions">
  <%= f.button :submit %>
</div>
<% end %>

app/views/cocktails/edit.html.erb
<div class="new-image">
  <h1 class="text-center">Editing Cocktail</h1>
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-6 col-sm-offset-3">
        <div class="new">
          <div class="new-body">
            <%= render 'form', cocktail: @cocktail %>
          </div>
          <%= link_to 'Show', @cocktail, class: "btn btn-primary" %> |
          <%= link_to 'Back', cocktails_path, class: "btn btn-warning" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/cocktails/index.html.erb
<div class="image">
  <div class="banner">
    <div class="banner-content">
      <h1>Cocktails</h1>
      <h3>Find. Share. Enjoy</h3>
      <a href="#card-id" class="btn btn-primary lg" style="padding: 17px 61px; font-size: 24px;">Start now</a>
    </div>
  </div>
</div>
<div id="card-id">
  <div class="container">
    <h1 class="text-center">My cocktails</h1>
    <div class="row">
      <% @cocktails.each do |cocktail| %>
      <div class="col-xs-12 col-sm-4">
        <!-- insert <div class="card"> -->
        <div class="card">
          <%= link_to cocktail do %>
          <% if cocktail.photo? %>
          <div class="card-body" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path cocktail.photo, height: 300, width: 400, crop: :fill %>')">
            <% else %>
            <div class="card-body" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://z65ovrxjio4asccx3admgs10-wpengine.netdna-ssl.com/wp-content/uploads/sites/2/2015/09/Cocktail-Bar.jpg');)">
              <% end %>
              <div class="card-description">
                <h4><%=  truncate(cocktail.name.upcase, length: 20) %></h4>
                <p><%= cocktail.nbr_ingredient %> ingredient(s)</p>
              </div>
              <span class="category">Popular</span>
            </div>
            <% end %>
            <div class="card-footer">
              <div class="card-icon">
                <%= link_to cocktail do %>
                <i class="fa fa-expand a" aria-hidden="true"></i>
                <% end %>
                <%= link_to edit_cocktail_path(cocktail) do %>
                <i class="fa fa-pencil a" aria-hidden="true"></i>
                <% end %>
                <%= link_to cocktail, method: :delete, data: { confirm: 'Are you sure?' } do %>
                <i class="fa fa-trash-o a" aria-hidden="true"></i>
                <% end %>
              </div>
              <div class="product">
                <div class='product-body'>
                  <h5>Votes</h5>
                </div>
                <div class='product-upvote'>
                <%= raise %>
                  <div class="product-arrow"></div>
                  <div class='product-count'><%= cocktail.vote %></div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <% end %>
        <div class="col-xs-12 col-sm-4">
          <!-- insert <div class="card"> -->
          <div class="card">
            <%= link_to new_cocktail_path do %>
            <div class="plus">
              <i class="fa fa-plus-square-o fa-5x" aria-hidden="true"></i>
            </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


<script>
  $(document).ready(function(){
    $('.product-upvote').click(function(event){
      this.add_vote;
    });
  });
</script>

app/views/cocktails/new.html.erb
<div class="new-image">
  <h1 class="text-center">New Cocktail</h1>
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-6 col-sm-offset-3">
        <div class="new">
          <div class="new-body">
            <%= render 'form', cocktail: @cocktail %>
          </div>
          <%= link_to 'Back', cocktails_path, class: "btn btn-warning" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/cocktails/show.html.erb
<div class="new-image" style="padding: 10px 70px 373px 70px;">
<br>
<h1 class="text-center">Ingredients of the <%= @cocktail.name %></h1>
<br>
  <div class="container text-center", style="background: white; opacity: 0.8;">
    <table>
      <thead>
        <tr>
          <th style="text-align: center" >Ingredients</th>
          <th style="text-align: center" >Doses</th>
          <th style="text-align: center" >Remove</th>
        </tr>
      </thead>

      <tbody>
        <% @doses.each do |dose| %>
        <tr>
          <td><%= dose.ingredient.name %></td>
          <td><%= dose.description %></td>
          <td><%= link_to 'Delete this dose', dose_path(dose.id), method: :delete %></td>
        </tr>
        <% end %>
      </tbody>
    </table>

    <%= link_to 'Add ingredients', new_cocktail_dose_path(@cocktail), class: "btn btn-primary button" %>
    <%= link_to 'Back', cocktails_path, class: "btn btn-warning button" %>
  </div>
</div>

app/views/doses/_form.html.erb
<%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :description, placeholder: "20cl of ..." %>
    <%= f.association :ingredient %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/doses/edit.html.erb
<h1>Editing Dose</h1>

<%= render 'form', dose: @dose %>

<%= link_to 'Show', @dose %> |
<%= link_to 'Back', doses_path %>

app/views/doses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Doses</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Cocktail</th>
      <th>Ingredient</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @doses.each do |dose| %>
      <tr>
        <td><%= dose.description %></td>
        <td><%= dose.cocktail %></td>
        <td><%= dose.ingredient %></td>
        <td><%= link_to 'Show', dose %></td>
        <td><%= link_to 'Edit', edit_dose_path(dose) %></td>
        <td><%= link_to 'Destroy', dose, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dose', new_dose_path %>

app/views/doses/new.html.erb
<div class="new-image">
  <h1 class="text-center">New Dose</h1>
  <div class="container", style="border-radius: 4px;">
    <div class="row">
      <div class="col-xs-12 col-sm-6 col-sm-offset-3">
        <div class="new">
          <div class="new-body">
            <%= render 'form', dose: @dose %>
          </div>
          <%= link_to 'Back', cocktail_path(@cocktail), class: "btn btn-warning" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/doses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @dose.description %>
</p>

<p>
  <strong>Cocktail:</strong>
  <%= @dose.cocktail %>
</p>

<p>
  <strong>Ingredient:</strong>
  <%= @dose.ingredient %>
</p>

<%= link_to 'Edit', edit_dose_path(@dose) %> |
<%= link_to 'Back', doses_path %>

app/views/ingredients/_form.html.erb
<%= simple_form_for(@ingredient) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/ingredients/edit.html.erb
<h1>Editing Ingredient</h1>

<%= render 'form', ingredient: @ingredient %>

<%= link_to 'Show', @ingredient %> |
<%= link_to 'Back', ingredients_path %>

app/views/ingredients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ingredients</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ingredients.each do |ingredient| %>
      <tr>
        <td><%= ingredient.name %></td>
        <td><%= link_to 'Show', ingredient %></td>
        <td><%= link_to 'Edit', edit_ingredient_path(ingredient) %></td>
        <td><%= link_to 'Destroy', ingredient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ingredient', new_ingredient_path %>

app/views/ingredients/new.html.erb
<h1>New Ingredient</h1>

<%= render 'form', ingredient: @ingredient %>

<%= link_to 'Back', ingredients_path %>

app/views/ingredients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @ingredient.name %>
</p>

<%= link_to 'Edit', edit_ingredient_path(@ingredient) %> |
<%= link_to 'Back', ingredients_path %>

app/views/layouts/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fa fa-github"></i></a>
    <a href="#"><i class="fa fa-instagram"></i></a>
    <a href="#"><i class="fa fa-facebook"></i></a>
    <a href="#"><i class="fa fa-twitter"></i></a>
    <a href="#"><i class="fa fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fa fa-heart"></i> at Le Wagon
  </div>
</div>

app/views/layouts/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <a href="/" class="navbar-wagon-brand">
    <%= image_tag("logo.jpeg") %>
  </a>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <!-- Profile picture with dropdown list -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <img src="https://kitt.lewagon.com/placeholder/users/ericrouach" class="avatar dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown">
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><a href="#">Profile</a></li>
          <li><a href="#">Dashboard</a></li>
          <li><a href="#">Log Out</a></li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsMisterCocktail</title>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link href="https://fonts.googleapis.com/css?family=Dancing+Script|Francois+One" rel="stylesheet">
</head>

<body>
  <%= render 'layouts/navbar' %>
  <%= yield %>
  <%= render 'layouts/footer' %>
</body>
</html>